# ---
# chapter: 28
# topic: Ollama Modelfile 自定义模型 (真实生成 + ollama create)
# section: 28.4.2 Ollama 一键部署
# difficulty: ⭐⭐⭐⭐
# tier: gpu
# deps: ollama (CLI)
# run: python 06_ollama_modelfile.py
# expected_runtime: <5s (生成 Modelfile) + ~30-120s (ollama create)
# expected_output: 真实写入 code/models/Modelfile + 调用 `ollama create` 创建模型
# ---
# See: ../tutorial/28_端侧与边缘LLM.md § 28.4.2
# Interview hooks:
#   1. Ollama Modelfile 相比直接用 GGUF 模型增加了哪些能力?
#   2. SYSTEM 指令在端侧 LLM 中如何影响行为?
#   3. 如何用 ADAPTER 字段加载 LoRA 微调权重?
"""Ollama Modelfile 模板生成器 - 真实写文件 + 真实调用 `ollama create`."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

# 让脚本既能 `python file.py` 也能 `import` 找到 shared/
_code_root = Path(__file__).resolve().parent.parent.parent
if str(_code_root) not in sys.path:
    sys.path.insert(0, str(_code_root))

from shared._error_helper import raise_with_help
from shared.gpu_guard import skip_if_mock


def _default_modelfile_path() -> str:
    """默认 Modelfile 路径: <repo>/code/models/Modelfile (相对脚本计算, 与 cwd 无关)."""
    return str(_code_root / "models" / "Modelfile")


def generate_modelfile(
    base_model: str = "llama3.2:3b",
    output_path: str = "",
) -> str:
    """生成 Ollama Modelfile (FROM + PARAMETER + TEMPLATE), 写入磁盘.

    相比旧版 (只 print 字符串), 现在真实写文件, 可被 `ollama create -f` 引用.

    Args:
        base_model: 基础模型名 (e.g. "llama3.2:3b").
        output_path: 写入路径, 默认 <repo>/code/models/Modelfile.
    """
    if not output_path:
        output_path = _default_modelfile_path()
    content = f"""# Ollama Modelfile (auto-generated by 06_ollama_modelfile.py)
# 用法: ollama create my-model -f {output_path}

FROM {base_model}

# === 参数 ===
PARAMETER temperature 0.7
PARAMETER top_p 0.9
PARAMETER top_k 40
PARAMETER num_ctx 4096

# === 系统提示词 ===
SYSTEM \"\"\"你是一个有帮助的 AI 助手, 回答简洁准确.\"\"\"

# === 模板 (Ollama 自动处理 chat format, 显式给出 Llama-3 chat template) ===
TEMPLATE \"\"\"<|begin_of_text|><|start_header_id|>system<|end_header_id|>

{{{{ .System }}}}<|eot_id|><|start_header_id|>user<|end_header_id|>

{{{{ .Prompt }}}}<|eot_id|><|start_header_id|>assistant<|end_header_id|>

{{{{ .Response }}}}<|eot_id|>
\"\"\"
"""
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content, encoding="utf-8")
    return str(out)


def create_ollama_model(modelfile_path: str, model_name: str = "tutorial-llama") -> str:
    """调用 `ollama create` 真实创建本地模型.

    Returns:
        model_name (创建成功的模型名)
    """
    import shutil

    if not shutil.which("ollama"):
        raise_with_help(
            "ollama CLI 未装或不在 PATH.",
            "访问 https://ollama.com/download 下载安装.",
        )

    try:
        result = subprocess.run(
            ["ollama", "create", model_name, "-f", modelfile_path],
            capture_output=True,
            text=True,
            timeout=180,
        )
    except subprocess.TimeoutExpired:
        raise_with_help(
            f"`ollama create {model_name}` 超时 (180s).",
            "可能是基础模型未下载; 尝试先 `ollama pull <base_model>`.",
        )

    if result.returncode != 0:
        raise_with_help(
            f"ollama create 失败 (rc={result.returncode}).\nstderr: {result.stderr.strip()}",
            "确保 `ollama serve` 在后台运行; 检查 Modelfile 语法; 检查 base_model 是否已 pull.",
        )

    return model_name


def main() -> None:
    if skip_if_mock("Ollama CLI、运行中的服务和基础模型"):
        return
    # 1. 真实写 Modelfile 到磁盘
    modelfile = generate_modelfile()
    print(f"Modelfile 已写入: {modelfile}")
    print("=" * 60)
    print(Path(modelfile).read_text(encoding="utf-8"))
    print("=" * 60)

    # 2. 真实调用 `ollama create`
    model = create_ollama_model(modelfile, "tutorial-llama")
    print(f"模型已创建: {model}")

    # 3. 给用户后续命令提示
    print(f"\n测试命令: ollama run {model} '讲个笑话'")


if __name__ == "__main__":
    main()
